services:
  file-server:
    build: .
    container_name: file-server
    ports:
      - "8089:8080"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8089"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s